x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prowlarr.svg
  urls:
    - https://prowlarr.com/
    - https://github.com/Prowlarr/Prowlarr

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-9696}:9696"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ${BASE_PATH}/config:/config
      - ${DOWNLOADS_PATH}:/downloads
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prowlarr.svg
