x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg
  urls:
    - https://sonarr.tv/
    - https://github.com/Sonarr/Sonarr

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8989}:8989"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ${BASE_PATH}/config:/config
      - ${TV_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg
