x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg
  urls:
    - https://radarr.video/
    - https://github.com/Radarr/Radarr

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT:-7878}:7878"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ${BASE_PATH}/config:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg
